import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bulma/css/bulma.min.css';


import NavBar from './components/navbar'
import Footer from './components/footer'
import Carousel from './components/swiper';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="has-navbar-fixed-top"  lang="en"><body className={inter.className}>
      <NavBar />
      {children}
      <Footer />
    </body>
    </html>
  )
}
